### PR TITLE
Add Nav bar

### PR DESCRIPTION
**Pull request by benyam7**
Feature:
- Navigation

_I tried to use free icons that can represent titles, feel free to edit them_

navbar1

navabar2

### CODE REVIEW

**Comment by sameeerkashyap** [comment]
Looks good to me, although not sure about the design choice of this. The theme changer was pretty good too. 

Maybe, @suhanichawla and @sachsom95 can drop in their opinions?

**Comment by saum7800** [comment]
Navbar is looking quite nice. I personally like the icons. I do have a couple of suggestions for the design.
1. The height of the navbar could be made lesser I feel since the icons are small.
2. When you hover over the icons, there are these 2 lines that come underneath the symbol. Not sure if that looks great.
3. The colour of the icons could be tweaked maybe to a darker shade? (might be totally wrong about this, maybe worth a try)

Would love @suhanichawla 's opinions on whether these changes would help.

**Comment by benyam7** [comment]
> Looks good to me, although not sure about the design choice of this. The theme changer was pretty good too.
> 
> Maybe, @suhanichawla and @sachsom95 can drop in their opinions?
thanks, @Sameerkash Sure, I can still incorporate the theme changing feature.

**Comment by benyam7** [comment]
thanks for the insightful comments @saum7800 , I will make the changes.

**Comment by benyam7** [comment]
@Sameerkash what kind of design would you suggest for having both nav bar icons and theme changer. I feel like it will be cluttered or sth. anyone who has thoughts is welcome :)

**Comment by sachsom95** [comment]
I really like the nav-bar definitely something I'd like in the website. Great Job. Heres my suggestions for desigh

- The height of navbar could be reduced a bit.
- The nav color complements the white background well, but when we check it under a darker background it seems to be not so good, especially the blue icon on black is difficult to pick up
- The sticky footer seems to have an issue on user experience eg here
Screenshot 2021-02-06 at 20 34 40

-  we may have better UX if dont float the nav above the page
-  There seemed to be an error with the nav event listner but on inspecting it may work well once we incorporate ur theme toggle 


Overall i'd like to have this in our webpage well done Benyam, Amazing work :)

**Comment by benyam7** [comment]
@sachsom95 Thank you very much! I tried some new fix measures feel free to check the new changes down below. I made the nav bar to hide on scroll to avoid nav bar floating.

**Comment by benyam7** [comment]
@Sameerkash @saum7800 @sachsom95 here are the changes i applied.

demo-6

**Comment by benyam7** [comment]
Also, the MLH logo being stuck at the top left corner without margin is an effect of the recorder I used. it's much better than that :)

**Review by saum7800 — APPROVED** [review]
I think it is looking amazing now! Great work Benyam!

**Comment by benyam7** [comment]
Thank you @saum7800 !

**Pull request merged**
